/**
 * Generator: tokens.json -> dist/{theme.css, tailwind.preset.ts, tokens.figma.json, tokens.d.ts}
 *
 * Nothing here is hand-maintained downstream. Editing a generated artifact is
 * always the wrong move — change tokens.json and rebuild.
 */

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { flatten, loadTokens, resolveAlias, type TokenTree } from './tokens.js'

/** DTCG `$type` per primitive group, used by the Figma export. */
const GROUP_TYPES: Readonly<Record<string, string>> = {
  color: 'color',
  space: 'dimension',
  text: 'dimension',
  leading: 'number',
  radius: 'dimension',
  duration: 'duration',
  easing: 'cubicBezier',
  font: 'fontFamily',
  shadow: 'shadow',
}

/** `space.4` -> `--gt-space-4` */
function primitiveVar(path: string): string {
  return `--gt-${path.replace(/\./g, '-')}`
}

function semanticGroup(tree: TokenTree, theme: string): TokenTree {
  const semantic = tree['semantic']
  if (semantic === undefined) throw new Error('tokens.json has no "semantic" group')
  const group = (semantic as TokenTree)[theme]
  if (group === undefined) throw new Error(`tokens.json has no "semantic.${theme}" group`)
  return group as TokenTree
}

function semanticNames(tree: TokenTree): string[] {
  return [...flatten(semanticGroup(tree, 'light')).keys()]
}

function block(selector: string, lines: readonly string[], indent = ''): string {
  const body = lines.map((line) => `${indent}  ${line}`).join('\n')
  return `${indent}${selector} {\n${body}\n${indent}}\n`
}

export function renderThemeCss(tree: TokenTree): string {
  const primitives = flatten(tree['primitive'] as TokenTree)
  const names = semanticNames(tree)

  const themeMap = [
    ...names.map((name) => `--color-${name}: var(--${name});`),
    '--radius-sm: calc(var(--radius) - 4px);',
    '--radius-md: calc(var(--radius) - 2px);',
    '--radius-lg: var(--radius);',
    '--radius-xl: calc(var(--radius) + 4px);',
    '--font-display: var(--gt-font-display);',
    '--font-sans: var(--gt-font-sans);',
    '--font-mono: var(--gt-font-mono);',
  ]

  const rootLines = [
    ...[...primitives].map(
      ([path, value]) => `${primitiveVar(path)}: ${resolveAlias(tree, value)};`,
    ),
    '--radius: var(--gt-radius-base);',
    ...names.map((name) => `--${name}: ${resolveAlias(tree, `{semantic.light.${name}}`)};`),
  ]

  const darkLines = names.map(
    (name) => `--${name}: ${resolveAlias(tree, `{semantic.dark.${name}}`)};`,
  )

  const reducedMotion = block(
    ':root',
    ['--gt-duration-fast: 1ms;', '--gt-duration-base: 1ms;', '--gt-duration-slow: 1ms;'],
    '  ',
  )

  return [
    '/* GENERATED by @globetrotter/design-system — edit tokens.json, never this file. */',
    '',
    block('@theme inline', themeMap),
    block(':root', rootLines),
    block('.dark', darkLines),
    `@media (prefers-reduced-motion: reduce) {\n${reducedMotion}}\n`,
  ].join('\n')
}

export function renderTailwindPreset(tree: TokenTree): string {
  const names = semanticNames(tree)
  const primitives = flatten(tree['primitive'] as TokenTree)

  const entries = (group: string): string =>
    [...primitives]
      .filter(([path]) => path.startsWith(`${group}.`))
      .map(([path, value]) => `      '${path.slice(group.length + 1)}': '${resolveAlias(tree, value)}',`)
      .join('\n')

  return `// GENERATED by @globetrotter/design-system — edit tokens.json, never this file.
// Tailwind v4 reads tokens from dist/theme.css via @theme. This preset exists
// for the places that need JS access to the same values.

export default {
  theme: {
    extend: {
      colors: {
${names.map((name) => `        '${name}': 'var(--${name})',`).join('\n')}
      },
      spacing: {
${entries('space')}
      },
      fontSize: {
${entries('text')}
      },
      borderRadius: {
        DEFAULT: 'var(--radius)',
      },
      boxShadow: {
${entries('shadow')}
      },
      fontFamily: {
${entries('font')}
      },
      transitionDuration: {
${entries('duration')}
      },
      transitionTimingFunction: {
${entries('easing')}
      },
    },
  },
} as const
`
}

/** Recursively copy the tree, adding `$type` to every leaf based on its group. */
function withTypes(node: TokenTree, group: string): Record<string, unknown> {
  const out: Record<string, unknown> = {}
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith('$')) continue
    const value = (child as { $value?: unknown })['$value']
    if (typeof value === 'string') {
      out[key] = { $value: value, $type: GROUP_TYPES[group] ?? 'other' }
    } else {
      // One level below `primitive`, the key names the group whose type applies.
      const nextGroup = group === '' ? key : group
      out[key] = withTypes(child as TokenTree, nextGroup)
    }
  }
  return out
}

export function renderFigmaTokens(tree: TokenTree): string {
  const primitive = tree['primitive']
  const semantic = tree['semantic']
  if (primitive === undefined || semantic === undefined) {
    throw new Error('tokens.json must contain both "primitive" and "semantic" groups')
  }
  return `${JSON.stringify(
    {
      primitive: withTypes(primitive as TokenTree, ''),
      semantic: withTypes(semantic as TokenTree, 'color'),
    },
    null,
    2,
  )}\n`
}

export function renderTypeDeclarations(tree: TokenTree): string {
  const semantic = semanticNames(tree)
  const primitive = [...flatten(tree['primitive'] as TokenTree).keys()].map((path) =>
    path.replace(/\./g, '-'),
  )
  const union = (values: readonly string[]): string =>
    values.map((value) => `  | '${value}'`).join('\n')

  return `// GENERATED by @globetrotter/design-system — edit tokens.json, never this file.

/** Every semantic token. Components reference these and nothing else. */
export type SemanticToken =
${union(semantic)}

/** Every primitive token, exposed as --gt-<name>. Not for use in components. */
export type PrimitiveToken =
${union(primitive)}
`
}

function main(): void {
  const tokensPath = fileURLToPath(new URL('../tokens.json', import.meta.url))
  const tree = loadTokens(tokensPath)
  const outDir = fileURLToPath(new URL('.', import.meta.url))

  const artifacts: ReadonlyArray<readonly [string, string]> = [
    ['theme.css', renderThemeCss(tree)],
    ['tailwind.preset.ts', renderTailwindPreset(tree)],
    ['tokens.figma.json', renderFigmaTokens(tree)],
    ['tokens.d.ts', renderTypeDeclarations(tree)],
  ]

  for (const [name, contents] of artifacts) {
    writeFileSync(`${outDir}${name}`, contents, 'utf8')
    console.log(`wrote dist/${name}`)
  }
}

const invokedDirectly =
  process.argv[1] !== undefined && import.meta.url === `file:///${process.argv[1].replace(/\\/g, '/')}`

if (invokedDirectly) {
  main()
}
